export const ACTION_TYPES = {
  EXAMPLE_INCREAMENT_COUNTER: "INCREAMENT_COUNTER",
  EXAMPLE_DECREAMENT_COUNTER: "DECREAMENT_COUNTER",
};

export const LAZY_LOAD_TYPE = {
  SET_DATA: "SET_LAZY_LOADING",
  ON_GRAB_DATA: "LAZY_LOADING_GRAB_DATA",
};